### PR TITLE
Added photos for all users, except the ones who haven't submitted pho…

### PR DESCRIPTION
**Pull request by joelbeckum**
…tos. They are now Andy. When all is dust, only Andy will remain.

### CODE REVIEW

**Comment by pracinejr** [comment]
💯

**Review by IanJames2 — APPROVED** [review]
👍🏾 I am shocked that many people did not turn in their selfies lol

**Comment by scarbine** [comment]
👍

**Comment by luzm321** [comment]
😎

**Review by ambarnett — COMMENTED** [review]
💯

**Pull request merged**
